# Indentation is important in this file
version: "3.9"

services: # all containers defined in the services
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  web:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db

